clear // Clear any existing data in memory

// Importing a CSV file named "mydata.csv" located in the specified path
import delimited "C:\Users\DONKAMS\Downloads\Sales-and-Customer-Analysis-\MegaSuperStore\Sample_-_Superstore.csv", clear firstrow

// Save your dataset if needed
save "C:\Users\DONKAMS\Downloads\Sales-and-Customer-Analysis-", replace

* manually reset the first rows as variable names
import delimited "C:\Users\DONKAMS\Downloads\Sales-and-Customer-Analysis-\MegaSuperStore\Sample_-_Superstore.csv", clear varnames(1)

browse

* summary statistics of the whole dataset
summarize

*stat for categorical variables
tabulate shipmode
tabulate city 
tabulate state
tabulate region 
tabulate category 
tabulate subcategory

* SALES TREND OVER TIME 
// Assuming orderdate is in string format, convert it to Stata's date format
gen date = date(orderdate, "DMY")

// Sort the data by date
sort date

// Declare the data as a time series using the date variable
tsset date

// Plot sales over time
tsline sales

duplicates report date

* aggregrate data by dates
collapse (sum) sales, by(date)

tsset date

browse date

use "C:\Users\DONKAMS\Downloads\Sales-and-Customer-Analysis-\Superstore_Stata_Data.dta", clear
describe

* SALES PERFORMANCE ANALYSIS
* What is the total sales volume over the entire period?
summarize sales

* How does sales volume vary across different product categories?
* Aggregate Sales by Category
collapse (sum) sales, by(category)

* Visualize Sales across all categories
graph bar (sum) sales, over(category) ///
    title("Sales Volume Across Product Categories") ///
    ytitle("Total Sales Volume")
	

* PROFITABILITY
* What is the overall profit generated by the business?
* Calculate Overall Profit
summarize profit, meanonly

*Which product categories contribute most to the overall profit margin?
collapse (sum) profit, by(category)
sort profit
browse

* Customer Analysis:
* How many unique customers made purchases in the dataset?
*Can we identify high-value or repeat customers based on their purchase behavior?
egen unique_customers = group(customerid)
count if unique_customers == 1
collapse (sum) sales, by(customerid)
collapse (mean) sales, by(customerid)
browse

* GEOGRAPHICAL INSIGHTS
collapse (sum) sales, by(region)
collapse (sum) sales, by(city)

* identify top regions based on sales
sort sales
list region sales in 1/10

* identify top cities based on sales
sort sales
list city sales in 1/10


